# Generated by Django 4.2.16 on 2024-11-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='sevice',
            new_name='service',
        ),
    ]
