# Generated by Django 4.2.16 on 2024-11-17 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_sevice_appointment_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
    ]
