# Generated by Django 4.2.16 on 2024-11-17 04:33

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_remove_appointment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=now),  # 変更点
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=now),  # 変更点
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "予約済み"),
                    ("cancelled", "キャンセル"),
                    ("completed", "完了"),
                ],
                default="booked",
                max_length=20,
            ),
        ),
    ]
