# Generated by Django 4.2.16 on 2024-11-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_appointment_created_at_appointment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('date', 'time', 'service'), name='unique_appointment_per_service'),
        ),
    ]
